apiVersion: v1
data:
  FRONTEND_URL: http://frontend.onenumber.svc.cluster.local:3000
  MONGO_URI: mongodb://mongodb-0.mongodb.onenumber.svc.cluster.local:27017,mongodb-1.mongodb.onenumber.svc.cluster.local:27017,mongodb-2.mongodb.onenumber.svc.cluster.local:27017/onenumber?replicaSet=rs0
  NODE_ENV: production
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: backend-configmap
